---
title: "Reproducible Research: Peer Assessment 1"
output: 
  html_document:
    keep_md: true
---
### Jason Seril
#### March 7, 2019

## Loading and preprocessing the data
```{r}
knitr::opts_chunk$set(warning=FALSE)
library(ggplot2)
activity <- read.csv("activity.csv")
activity$date <- as.Date(activity$date, "%Y-%m-%d")
weekday <- weekdays(activity$date)
activity <- cbind(activity,weekday)

summary(activity)
```

## What is mean total number of steps taken per day?
```{r}
activityTotalSteps <- with(activity, aggregate(steps, by=list(date), FUN=sum, 
                                                 na.rm=TRUE))
names(activityTotalSteps) <- c("date","steps")
hist(activityTotalSteps$steps, main="Total number of steps taken per day",
     xlab="Total steps taken per day", col="darkblue", ylim=c(0,20), 
     breaks=seq(0,25000, by=2500))
```


## What is the average daily activity pattern?



## Imputing missing values



## Are there differences in activity patterns between weekdays and weekends?
